"""Contracts used by application services; no SDK or filesystem imports."""
from dataclasses import dataclass
from typing import Any, Protocol


@dataclass(frozen=True)
class Choice:
    name: str
    value: str


class VoiceConnection(Protocol):
    channel: Any
    guild: Any
    source: Any

    def is_connected(self) -> bool: ...
    def is_playing(self) -> bool: ...
    def is_paused(self) -> bool: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def stop(self) -> None: ...
    def play(self, source: Any, *, after: Any) -> None: ...
    async def disconnect(self, *, force: bool = False) -> None: ...


class SettingsRepository(Protocol):
    def read(self, section: str, guild_id=None) -> dict: ...
    def write(self, section: str, settings: dict, guild_id=None) -> None: ...


class RuntimeRepository(Protocol):
    def read_status(self) -> dict: ...
    def enqueue_control(self, command: dict) -> str: ...
    def write_status(self, **updates: Any) -> bool: ...
    def write_music_session(self, session_id: str, data: dict) -> bool: ...
    def remove_music_session(self, session_id: str) -> bool: ...
    def drain_control_commands(self) -> list[dict]: ...
    def write_control_result(self, command: dict, ok: bool, message: str) -> bool: ...
    def read_control_result(self, command_id: str) -> dict | None: ...


class LogReader(Protocol):
    def read(self, limit: int, guild_id=None, level="INFO", details=False) -> list[str]: ...
